[server]
enableWebsocketCompression=false
enableCORS=false
enableXsrfProtection=false


[theme]

primaryColor = '#FF0000'
backgroundColor = '#FCFCFC'
secondaryBackgroundColor = '#DCDCDC'
textColor = '#000000'
