[server]
enableWebsocketCompression=false
enableCORS=false
enableXsrfProtection=false


[theme]
primaryColor = '#070707'
backgroundColor = '#fcfcfc'
secondaryBackgroundColor = '#e3e3e3'
textColor = '#070707'
